### ISSUE TITLE
fresh install of latest release does not work with python 3.9

### ISSUE THREAD

**Issue by rbavery** [datatorch/python#6]
to reproduce:

`pip install datatorch`

then

`dt`

results in this error

```python
# rave at rave-desktop in ~/datatorch on git:master ✖︎ [12:07:45]
→ datatorch
Traceback (most recent call last):
  File "/home/rave/miniconda3/envs/datatorchtest/bin/datatorch", line 5, in <module>
    from datatorch.cli import main
  File "/home/rave/miniconda3/envs/datatorchtest/lib/python3.9/site-packages/datatorch/__init__.py", line 4, in <module>
    from datatorch.api import ApiClient
  File "/home/rave/miniconda3/envs/datatorchtest/lib/python3.9/site-packages/datatorch/api/__init__.py", line 1, in <module>
    from .api import ApiClient
  File "/home/rave/miniconda3/envs/datatorchtest/lib/python3.9/site-packages/datatorch/api/api.py", line 7, in <module>
    from .client import Client
  File "/home/rave/miniconda3/envs/datatorchtest/lib/python3.9/site-packages/datatorch/api/client.py", line 5, in <module>
    from gql.transport.websockets import WebsocketsTransport
  File "/home/rave/miniconda3/envs/datatorchtest/lib/python3.9/site-packages/gql/transport/websockets.py", line 11, in <module>
    from websockets.http import HeadersLike
ImportError: cannot import name 'HeadersLike' from 'websockets.http' (/home/rave/miniconda3/envs/datatorchtest/lib/python3.9/site-packages/websockets/http.py)
(datatorchtest) 
```

I ran this in a fresh python environment with python 3.9

**Comment by rbavery** [comment]
This error also occurs in a python 3.6 environment: 
```python
(datatorchtest) 
# rave at rave-desktop in ~/datatorch on git:master ✖︎ [12:10:27]
→ dt       
Traceback (most recent call last):
  File "/home/rave/miniconda3/envs/datatorchtest/bin/dt", line 5, in <module>
    from datatorch.cli import main
  File "/home/rave/miniconda3/envs/datatorchtest/lib/python3.6/site-packages/datatorch/__init__.py", line 4, in <module>
    from datatorch.api import ApiClient
  File "/home/rave/miniconda3/envs/datatorchtest/lib/python3.6/site-packages/datatorch/api/__init__.py", line 1, in <module>
    from .api import ApiClient
  File "/home/rave/miniconda3/envs/datatorchtest/lib/python3.6/site-packages/datatorch/api/api.py", line 7, in <module>
    from .client import Client
  File "/home/rave/miniconda3/envs/datatorchtest/lib/python3.6/site-packages/datatorch/api/client.py", line 5, in <module>
    from gql.transport.websockets import WebsocketsTransport
  File "/home/rave/miniconda3/envs/datatorchtest/lib/python3.6/site-packages/gql/transport/websockets.py", line 11, in <module>
    from websockets.http import HeadersLike
ImportError: cannot import name 'HeadersLike'
```

**Comment by ninthreezy** [comment]
We are looking at this now.

**Comment by ninthreezy** [comment]
It should work now.
